--- 
title: "Remote Learning Preferences Analysis"
author: "Alexandra Jalali, Liang Zhuang, Victoria Xu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction
The COVID-19 pandemic has presented significant challenges to education. Schools and professors had to change their educational tools and teaching methods to accommodate an unfamiliar learning environment. Students were forced to start learning pivotal foundational topics, such as counting and reading, from their kitchen counters. As college students whose lives are strongly impacted by the pandemic, we are curious about the impact of remote learning on the performance of students. Additionally, we want to see if an individual's demographic, such as gender or race, affects their preference for remote learning. We will use data from the NYC Department of Education to see if there is any correlation between remote learning preference and test scores from 2019 to 2022. We will also examine demographic factors such as gender, English learner status, and race/ethnicity to see if any patterns emerge that affect students' preferences and test scores.

The goal of our project is to explain and visualize data on our analysis of students’ remote learning preferences. A student's preference for remote learning may depend on their comfort level with learning at home and their dependence on school resources such as computers and cafeterias. By examining patterns based on demographics and comparing pre- and post-pandemic test scores, we aim to gain a better understanding of the factors that influence students' preferences for remote learning. Our hope is that our findings will inspire future research and lead to practical solutions that ensure all children have access to a fair education.
