# Interactive component

<h2>This is the sample7</h2>

<meta charset="utf-8">
<style>

.background {
  fill: #eee;
  opacity: 0;
  pointer-events: all;
}

.map-layer {
  fill: #fff;
  stroke: #aaa;
}

.effect-layer{
  pointer-events:none;
}

text{
  font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
  font-weight: 300;
}

text.big-text{
  font-size: 30px;
  font-weight: 400;
}
text.medium-text{
  font-size: 15px;
  font-weight: 400;
}
text.small-text{
  font-size: 12px;
  font-weight: 1000;
}
.effect-layer text{
  font-size: 12px;
}

</style>
<body>


<script src="https://d3js.org/d3.v7.js"></script>
<div id = "graph2"></div>

<h2> This is the second graph </h2>

<div id = "graph1"></div>
<script>
var width = 1060,height = 720,centered;

const projection = d3.geoMercator()
  .scale(33000)
  .center([-73.935242, 40.730610])
  .translate([width / 4.6, height / 3.2]);
  
const projection2 = d3.geoMercator()
  .scale(45000)
  .center([-73.935242, 40.730610])
  .translate([width / 2, height / 2]);

const path = d3.geoPath()
  .projection(projection);

const path2 = d3.geoPath()
  .projection(projection2);

const svg = d3.select('div#graph1')
  .append('svg')
  .attr('width', width)
  .attr('height', height);

svg.append('rect')
  .attr('class', 'background')
  .attr('width', width)
  .attr('height', height);

svg.append("circle")
  .attr("cx",200)
  .attr("cy",130)
  .attr("r", 9)
  .style("fill", "orange")
  
svg.append("circle")
  .attr("cx",200)
  .attr("cy",160)
  .attr("r", 9)
  .style("fill", "lightblue")
  
svg.append("circle")
  .attr("cx",200)
  .attr("cy",190)
  .attr("r", 9)
  .style("fill", "green")
  
svg.append("circle")
  .attr("cx",200)
  .attr("cy",220)
  .attr("r", 9)
  .style("fill", "pink")

svg.append("circle")
  .attr("cx",200)
  .attr("cy",250)
  .attr("r", 9)
  .style("fill", "purple")

svg.append("text")
  .attr("x", 220)
  .attr("y", 130)
  .text("Manhattan")
  .style("font-size", "20px")
  .attr("alignment-baseline","middle")
  
svg.append("text")
  .attr("x", 220)
  .attr("y", 160)
  .text("Brooklyn")
  .style("font-size", "20px")
  .attr("alignment-baseline","middle")
  
svg.append("text")
  .attr("x", 220)
  .attr("y", 190)
  .text("Bronx")
  .style("font-size", "20px")
  .attr("alignment-baseline","middle")
  
svg.append("text")
  .attr("x", 220)
  .attr("y", 220)
  .text("Queens")
  .style("font-size", "20px")
  .attr("alignment-baseline","middle")

svg.append("text")
  .attr("x", 220)
  .attr("y", 250)
  .text("Staten Island")
  .style("font-size", "20px")
  .attr("alignment-baseline","middle")

svg.append("text")
  .attr("x", 280)
  .attr("y", 25)
  .text("Find Your District: ")
  .style("font-size", "35px")
  .attr("alignment-baseline","middle")
  
const g = svg.append('g');

const effectLayer = g.append('g')
  .classed('effect-layer', true);

const mapLayer = g.append('g')
  .classed('map-layer', true);

const bigText = g.append('text')
  .classed('big-text', true)
  .attr('x', 550)
  .attr('y', 33);

d3.json('https://raw.githubusercontent.com/alexjalali/remotelearningedav/main/School%20Districts.geojson').then(function(mapData) {
  var features = mapData.features;

  mapLayer.selectAll('path')
      .data(features)
    .enter().append('path')
      .attr('d', path2)
      .attr('vector-effect', 'non-scaling-stroke')
      .style('fill', fill)
      .on('mouseover', mouseover)
      .on('mouseout', mouseout);
});

function name(d){
  return d.properties.school_dist;
}


function fill(d){
  if(parseInt(name(d)) <= 6) return "orange";
  if(String(name(d)) == "31") return "purple";
  if(parseInt(name(d)) <= 12 && parseInt(name(d)) >= 7) return "green";
  if(parseInt(name(d)) <= 30 && parseInt(name(d)) >= 24) return "pink";
  return "lightblue";
}

function mouseover(event, d){
  d3.select(this).style('fill', 'yellow');
  bigText
    .style('font-family', 'Helvetica Neue')
    .text("District " + String(name(d)));
}

function mouseout(d){
  mapLayer.selectAll('path')
    .style('fill', function(d){return centered && d===centered ? '#D5708B' : fill(d);});

  effectLayer.selectAll('text').transition()
    .style('opacity', 0)
    .remove();
  bigText
    .text("");
}


const svg2 = d3.select('div#graph2')
  .append('svg')
  .attr('width', width)
  .attr('height', height);

svg2.append('rect')
  .attr('class', 'background')
  .attr('width', width)
  .attr('height', height);

const g2 = svg2.append('g');

const effectLayer2 = g2.append('g')
  .classed('effect-layer', true);

const mapLayer2 = g2.append('g')
  .classed('map-layer', true);

const bigText2 = g2.append('text')
  .classed('big-text', true)
  .attr('x', 30)
  .attr('y', 25);
  
const remotelearning = g2.append('text')
  .classed('medium-text', true)
  .attr('x', 33)
  .attr('y', 50);

const mediumText1 = g2.append('text')
  .classed('small-text', true);

const mediumText2 = g2.append('text')
  .classed('small-text', true);

const mediumText3 = g2.append('text')
  .classed('small-text', true);

const mediumText4 = g2.append('text')
  .classed('small-text', true);

g2.append('text')
  .classed('small-text', true)
  .attr('x', 77).attr('y', 125).text('75%');

g2.append('text')
  .classed('small-text', true)
  .attr('x', 77).attr('y', 144).text('70%');

g2.append('text')
  .classed('small-text', true)
  .attr('x', 77).attr('y', 163).text('65%');

g2.append('text')
  .classed('small-text', true)
  .attr('x', 77).attr('y', 182).text('60%');

g2.append('text')
  .classed('small-text', true)
  .attr('x', 77).attr('y', 201).text('55%');

g2.append('text')
  .classed('small-text', true)
  .attr('x', 77).attr('y', 220).text('50%');

g2.append("rect").attr('x', 40).attr('y', 119.2).attr('width', 30)
  .attr('height', 100).attr('fill', 'white').style('opacity',1).attr('stroke', 'black');
//created legend
g2.append("rect").attr('x', 40).attr('y', 120).attr('width', 30)
  .attr('height', 5).attr('fill', 'red').style('opacity',1);
g2.append("rect").attr('x', 40).attr('y', 125).attr('width', 30)
  .attr('height', 5).attr('fill', 'red').style('opacity',0.95);
g2.append("rect").attr('x', 40).attr('y', 130).attr('width', 30)
  .attr('height', 5).attr('fill', 'red').style('opacity',0.9);
g2.append("rect").attr('x', 40).attr('y', 135).attr('width', 30)
  .attr('height', 5).attr('fill', 'red').style('opacity',0.85);
g2.append("rect").attr('x', 40).attr('y', 140).attr('width', 30)
  .attr('height', 5).attr('fill', 'red').style('opacity',0.80);
g2.append("rect").attr('x', 40).attr('y', 145).attr('width', 30)
  .attr('height', 5).attr('fill', 'red').style('opacity',0.75);
g2.append("rect").attr('x', 40).attr('y', 150).attr('width', 30)
  .attr('height', 5).attr('fill', 'red').style('opacity',0.70);
g2.append("rect").attr('x', 40).attr('y', 155).attr('width', 30)
  .attr('height', 5).attr('fill', 'red').style('opacity',0.65);
g2.append("rect").attr('x', 40).attr('y', 160).attr('width', 30)
  .attr('height', 5).attr('fill', 'red').style('opacity',0.6);
g2.append("rect").attr('x', 40).attr('y', 165).attr('width', 30)
  .attr('height', 5).attr('fill', 'red').style('opacity',0.55);
g2.append("rect").attr('x', 40).attr('y', 170).attr('width', 30)
  .attr('height', 5).attr('fill', 'red').style('opacity',0.5);
g2.append("rect").attr('x', 40).attr('y', 175).attr('width', 30)
  .attr('height', 5).attr('fill', 'red').style('opacity',0.45);
g2.append("rect").attr('x', 40).attr('y', 180).attr('width', 30)
  .attr('height', 5).attr('fill', 'red').style('opacity',0.4);
g2.append("rect").attr('x', 40).attr('y', 185).attr('width', 30)
  .attr('height', 5).attr('fill', 'red').style('opacity',0.35);
g2.append("rect").attr('x', 40).attr('y', 190).attr('width', 30)
  .attr('height', 5).attr('fill', 'red').style('opacity',0.30);
g2.append("rect").attr('x', 40).attr('y', 195).attr('width', 30)
  .attr('height', 5).attr('fill', 'red').style('opacity',0.25);
g2.append("rect").attr('x', 40).attr('y', 200).attr('width', 30)
  .attr('height', 5).attr('fill', 'red').style('opacity',0.20);
g2.append("rect").attr('x', 40).attr('y', 205).attr('width', 30)
  .attr('height', 5).attr('fill', 'red').style('opacity',0.15);
g2.append("rect").attr('x', 40).attr('y', 210).attr('width', 30)
  .attr('height', 5).attr('fill', 'red').style('opacity',0.10);
g2.append("rect").attr('x', 40).attr('y', 215).attr('width', 30)
  .attr('height', 5).attr('fill', 'red').style('opacity',0.05);


var xAxis = d3.axisBottom()
.scale(d3.scaleBand().domain(['2018', '2022']).range([0,200]));

var yAxis = d3.axisLeft()
.scale(d3.scaleLinear().domain([650, 550]).range([0,150]));

const xAxisshow = g2.append('g')
    .attr("transform",`translate(${500},${210})`);

const yAxisshow = g2.append('g')
    .attr("transform",`translate(${500},${60})`);

const legendname = g2.append('text')
  .classed('small-text', true)
  .attr('x', 30)
  .attr('y', 105)
	.text('% remote');
//bar for graph1
const bar1 = g2.append("rect");
const bar2 = g2.append("rect");
const bar3 = g2.append("rect");
const bar4 = g2.append("rect");
//label for graph1
const xlabel = g2.append('text');
const ylabel = g2.append('text');
const chartname1 = g2.append('text')
  .classed('small-text', true);
const legend1 = g2.append("rect");
const legend2 = g2.append("rect");
const legendlabel1 = g2.append('text')
	.classed('small-text', true);
const legendlabel2 = g2.append('text')
	.classed('small-text', true);

//bar for graph2
const genderbar1 = g2.append("rect");
const genderbar2 = g2.append("rect");
const ethnicitybar1 = g2.append("rect");
const ethnicitybar2 = g2.append("rect");
const ethnicitybar3 = g2.append("rect");
const ethnicitybar4 = g2.append("rect");
const gradebar3 = g2.append("rect");
const gradebar4 = g2.append("rect");
const gradebar5 = g2.append("rect");
const gradebar6 = g2.append("rect");
const gradebar7 = g2.append("rect");
const gradebar8 = g2.append("rect");
const ellbar1 = g2.append("rect");
const ellbar2 = g2.append("rect");

//label for graph2
const xlabel2 = g2.append('text');
const ylabel2 = g2.append('text');
const chartname2 = g2.append('text')
  .classed('small-text', true);
  
var xAxis2 = d3.axisBottom()
.scale(d3.scaleBand().domain(['Gender', 'Race/Ethnicity', 'Grade Level', 'ELL Status']).range([0,320]));

var yAxis2 = d3.axisLeft()
.scale(d3.scaleLinear().domain([100,0]).range([0,207]));

const xAxisshow2 = g2.append('g')
    .attr("transform",`translate(${400},${465})`);

const yAxisshow2 = g2.append('g')
    .attr("transform",`translate(${400},${258})`);

const mediumText5 = g2.append('text')
  .classed('small-text', true);

const mediumText6 = g2.append('text')
  .classed('small-text', true);

const legend3 = g2.append("rect");
const legend4 = g2.append("rect");
const legend5 = g2.append("rect");
const legend6 = g2.append("rect");
const legend7 = g2.append("rect");
const legend8 = g2.append("rect");
const legend9 = g2.append("rect");
const legend10 = g2.append("rect");
const legend11 = g2.append("rect");
const legend12 = g2.append("rect");
const legend13 = g2.append("rect");
const legend14 = g2.append("rect");
const legend15 = g2.append("rect");
const legend16 = g2.append("rect");

const legendlabel3 = g2.append('text')
	.classed('small-text', true);
const legendlabel4 = g2.append('text')
	.classed('small-text', true);
const legendlabel5 = g2.append('text')
	.classed('small-text', true);
const legendlabel6 = g2.append('text')
	.classed('small-text', true);
const legendlabel7 = g2.append('text')
	.classed('small-text', true);
const legendlabel8 = g2.append('text')
	.classed('small-text', true);
const legendlabel9 = g2.append('text')
	.classed('small-text', true);
const legendlabel10 = g2.append('text')
	.classed('small-text', true);
const legendlabel11 = g2.append('text')
	.classed('small-text', true);
const legendlabel12 = g2.append('text')
	.classed('small-text', true);
const legendlabel13 = g2.append('text')
	.classed('small-text', true);
const legendlabel14 = g2.append('text')
	.classed('small-text', true);
const legendlabel15 = g2.append('text')
	.classed('small-text', true);
const legendlabel16 = g2.append('text')
	.classed('small-text', true);
  
const legendvalue3 = g2.append('text')
	.classed('small-text', true);
const legendvalue4 = g2.append('text')
	.classed('small-text', true);
const legendvalue5 = g2.append('text')
	.classed('small-text', true);
const legendvalue6 = g2.append('text')
	.classed('small-text', true);
const legendvalue7 = g2.append('text')
	.classed('small-text', true);
const legendvalue8 = g2.append('text')
	.classed('small-text', true);
const legendvalue9 = g2.append('text')
	.classed('small-text', true);
const legendvalue10 = g2.append('text')
	.classed('small-text', true);
const legendvalue11 = g2.append('text')
	.classed('small-text', true);
const legendvalue12 = g2.append('text')
	.classed('small-text', true);
const legendvalue13 = g2.append('text')
	.classed('small-text', true);
const legendvalue14 = g2.append('text')
	.classed('small-text', true);
const legendvalue15 = g2.append('text')
	.classed('small-text', true);
const legendvalue16 = g2.append('text')
	.classed('small-text', true);

d3.csv("https://raw.githubusercontent.com/alexjalali/remotelearningedav/main/datasets/DataClean.csv").then(function(data) {
  function opacity(d){
  const ArrayPercent = [];
	for (var i=1; i <= 32; i++){
    ArrayPercent.push(parseFloat(data[i*15-1].PercentRemote));
  }
  const min = d3.min(ArrayPercent)-4;
  const max = d3.max(ArrayPercent);
  return (ArrayPercent[parseInt(name(d))-1]-min)/(max-min);
  }
  function remote(d){
    const remotel = [];
    for (var i=1; i <= 32; i++){
    	remotel.push(parseFloat(data[i*15-1].PercentRemote));
  	}
    return remotel[parseInt(name(d))-1].toFixed(1);
  }
  function math19(d){
    const ArrayMath2019 = [];
    for (var i=1; i <= 32; i++){
    	ArrayMath2019.push(parseFloat(data[i*15-1].MathScores2019));
  	}
    return ArrayMath2019[parseInt(name(d))-1].toFixed(1);
  }
  
  function ela19(d){
    const ArrayELA2019 = [];
    for (var i=1; i <= 32; i++){
    	ArrayELA2019.push(parseFloat(data[i*15-1].ELAScores2019));
  	}
    return ArrayELA2019[parseInt(name(d))-1].toFixed(1);
  }
  
  function math22(d){
    const ArrayMath2022 = [];
    for (var i=1; i <= 32; i++){
    	ArrayMath2022.push(parseFloat(data[i*15-1].MathScores2022));
  	}
    return ArrayMath2022[parseInt(name(d))-1].toFixed(1);
  }
  
  function ela22(d){
    const ArrayELA2022 = [];
    for (var i=1; i <= 32; i++){
    	ArrayELA2022.push(parseFloat(data[i*15-1].ELAScores2022));
  	}
    return ArrayELA2022[parseInt(name(d))-1].toFixed(1);
  }
  
  function male(d){
    const Arraymale = [];
    for (var i=1; i <= 32; i++){
    	Arraymale.push(100 * parseFloat(data[(i-1)*15+3].TotalEnrollment)/(parseFloat(data[(i-1)*15+3].TotalEnrollment) + parseFloat(data[(i-1)*15+2].TotalEnrollment)));
  	}
    return Arraymale[parseInt(name(d))-1].toFixed(1);
  }
  
  function female(d){
    return 100-male(d);
  }
  function totalenthnicity(d){
    const ethnicity = [];
    for (var i=1; i <= 32; i++){
      ethnicity.push(parseFloat(data[(i-1)*15+10].TotalEnrollment) + parseFloat(data[(i-1)*15+11].TotalEnrollment) + parseFloat(data[(i-1)*15+12].TotalEnrollment) + parseFloat(data[(i-1)*15+13].TotalEnrollment))
    }
    return ethnicity[parseInt(name(d))-1];
  }
  
  function asian(d){
    const asianArray = [];
    for (var i=1; i <= 32; i++){
      asianArray.push(100*parseFloat(data[(i-1)*15+10].TotalEnrollment)/totalenthnicity(d))
    }
    return asianArray[parseInt(name(d))-1].toFixed(1);
  }
  
  function black(d){
    const blackArray = [];
    for (var i=1; i <= 32; i++){
      blackArray.push(100*parseFloat(data[(i-1)*15+11].TotalEnrollment)/totalenthnicity(d))
    }
    return blackArray[parseInt(name(d))-1].toFixed(1);
  }
  
  function hispanic(d){
    const hispanicArray = [];
    for (var i=1; i <= 32; i++){
      hispanicArray.push(100*parseFloat(data[(i-1)*15+12].TotalEnrollment)/totalenthnicity(d))
    }
    return hispanicArray[parseInt(name(d))-1].toFixed(1);
  }
  
  function white(d){
    const whiteArray = [];
    for (var i=1; i <= 32; i++){
      whiteArray.push(100*parseFloat(data[(i-1)*15+13].TotalEnrollment)/totalenthnicity(d))
    }
    return whiteArray[parseInt(name(d))-1].toFixed(1);
  }
  
  function totalgrade(d){
    const grade = [];
    for (var i=1; i <= 32; i++){
      grade.push(parseFloat(data[(i-1)*15+4].TotalEnrollment) + parseFloat(data[(i-1)*15+5].TotalEnrollment) + parseFloat(data[(i-1)*15+6].TotalEnrollment) + parseFloat(data[(i-1)*15+7].TotalEnrollment) + parseFloat(data[(i-1)*15+8].TotalEnrollment) + parseFloat(data[(i-1)*15+9].TotalEnrollment))
    }
    return grade[parseInt(name(d))-1];
  }
  
  function grade3(d){
    const grade3Array = [];
    for (var i=1; i <= 32; i++){
      grade3Array.push(100*parseFloat(data[(i-1)*15+4].TotalEnrollment)/totalgrade(d))
    }
    return grade3Array[parseInt(name(d))-1].toFixed(1);
  }
  
  function grade4(d){
    const grade4Array = [];
    for (var i=1; i <= 32; i++){
      grade4Array.push(100*parseFloat(data[(i-1)*15+5].TotalEnrollment)/totalgrade(d))
    }
    return grade4Array[parseInt(name(d))-1].toFixed(1);
  }
  
  function grade5(d){
    const grade5Array = [];
    for (var i=1; i <= 32; i++){
      grade5Array.push(100*parseFloat(data[(i-1)*15+6].TotalEnrollment)/totalgrade(d))
    }
    return grade5Array[parseInt(name(d))-1].toFixed(1);
  }
  
  function grade6(d){
    const grade6Array = [];
    for (var i=1; i <= 32; i++){
      grade6Array.push(100*parseFloat(data[(i-1)*15+7].TotalEnrollment)/totalgrade(d))
    }
    return grade6Array[parseInt(name(d))-1].toFixed(1);
  }
  
  function grade7(d){
    const grade7Array = [];
    for (var i=1; i <= 32; i++){
      grade7Array.push(100*parseFloat(data[(i-1)*15+8].TotalEnrollment)/totalgrade(d))
    }
    return grade7Array[parseInt(name(d))-1].toFixed(1);
  }
  
  function grade8(d){
    const grade8Array = [];
    for (var i=1; i <= 32; i++){
      grade8Array.push(100*parseFloat(data[(i-1)*15+9].TotalEnrollment)/totalgrade(d))
    }
    return grade8Array[parseInt(name(d))-1].toFixed(1);
  }
  
  function ELL(d){
    const ArrayELL = [];
    for (var i=1; i <= 32; i++){
    	ArrayELL.push(100 * parseFloat(data[(i-1)*15].TotalEnrollment)/(parseFloat(data[(i-1)*15+1].TotalEnrollment) + parseFloat(data[(i-1)*15].TotalEnrollment)));
  	}
    return ArrayELL[parseInt(name(d))-1].toFixed(1);
  }
  
  function NoELL(d){
    return 100-ELL(d);
  }
  
  function mouseover2(event, d){
  d3.select(this).style('fill', 'yellow').style('opacity', 1);
  bigText2
    .style('font-family', 'Helvetica Neue')
    .text("District " + String(name(d)));
  remotelearning
  	.style('font-family', 'Helvetica Neue')
    .text("Remote Learning Percentage: " + String(remote(d)) + "%");
  mediumText1
    .style('font-family', 'Helvetica Neue')
    .attr('x', 518)
  	.attr('y', 205-(math19(d)-550)*(150/100))
    .text(String(math19(d)));
  mediumText2
    .style('font-family', 'Helvetica Neue')
    .attr('x', 618)
  	.attr('y', 205-(math22(d)-550)*(150/100))
    .text(String(math22(d)));
  mediumText3
    .style('font-family', 'Helvetica Neue')
    .attr('x', 552)
  	.attr('y', 205-(ela19(d)-550)*(150/100))
    .text(String(ela19(d)));
  mediumText4
    .style('font-family', 'Helvetica Neue')
    .attr('x', 652)
  	.attr('y', 205-(ela22(d)-550)*(150/100))
    .text(String(ela22(d)));
  xAxisshow.call(xAxis);
	yAxisshow.call(yAxis);

  bar1.attr('x', 520)
    .attr('y', 210-(math19(d)-550)*(150/100)).attr('width', 30)
  	.attr('height', (math19(d)-550)*(150/100)).attr('fill', '#0492C2').attr('opacity', 0.8);
    
  bar2.attr('x', 550)
    .attr('y', 210-(ela19(d)-550)*(150/100)).attr('width', 30)
  	.attr('height', (ela19(d)-550)*(150/100)).attr('fill', '#597D35').attr('opacity', 0.8);
    
  bar3.attr('x', 620)
    .attr('y', 210-(math22(d)-550)*(150/100)).attr('width', 30)
  	.attr('height', (math22(d)-550)*(150/100)).attr('fill', '#0492C2').attr('opacity', 0.8);
  
  bar4.attr('x', 650)
    .attr('y', 210-(ela22(d)-550)*(150/100)).attr('width', 30)
  	.attr('height', (ela22(d)-550)*(150/100)).attr('fill', '#597D35').attr('opacity', 0.8);
  xlabel.classed('small-text', true).attr('x', 470).attr('y',45).text('Score');
  ylabel.classed('small-text', true).attr('x', 710).attr('y',215).text('Year');
  chartname1.attr('x', 520).attr('y', 55).text('Average Test Scores for 2018 & 2022');
  legend1.attr('x', 700).attr('y', 75).attr('width', 10)
  .attr('height', 10).attr('fill', '#0492C2').style('opacity',0.8);
  legend2.attr('x', 700).attr('y', 90).attr('width', 10)
  .attr('height', 10).attr('fill', '#597D35').style('opacity',0.8);
  legendlabel1.attr('x', 720).attr('y', 85).text('Math Score');
  legendlabel2.attr('x', 720).attr('y', 100).text('ELA Score');
  xAxisshow2.call(xAxis2);
	yAxisshow2.call(yAxis2);
  mediumText5.attr('x', 360).attr('y',243).text('Percentage');
  mediumText6.attr('x', 730).attr('y',470).text('Category');
  legend3.attr('x', 410).attr('y', 530).attr('width', 10)
  .attr('height', 10).attr('fill', '#800000').attr('opacity', 0.7);
  legend4.attr('x', 410).attr('y', 500).attr('width', 10)
  .attr('height', 10).attr('fill', '#008080').attr('opacity', 0.7);
  legendlabel3.attr('x', 430).attr('y', 540).text('Male');
  legendlabel4.attr('x', 430).attr('y', 509).text('Female');
  legendvalue3.attr('x', 430).attr('y', 525).text(female(d) + "%");
  legendvalue4.attr('x', 430).attr('y', 555).text(male(d) + "%");
  genderbar1.attr('x', 425)
    .attr('y', 465-(male(d))*(2.07)).attr('width', 30)
  	.attr('height', (male(d))*(2.07)).attr('fill', '#800000').attr('opacity', 0.7);
  genderbar2.attr('x', 425)
    .attr('y', 258).attr('width', 30)
  	.attr('height', (female(d))*(2.07))
    .attr('fill','#008080').attr('opacity', 0.7);
  legendlabel5.attr('x', 520).attr('y', 509).text('Asian');
  legendlabel6.attr('x', 520).attr('y', 540).text('Black');
  legendlabel7.attr('x', 520).attr('y', 570).text('Hispanic');
  legendlabel8.attr('x', 520).attr('y', 600).text('White');
  legendvalue5.attr('x', 520).attr('y', 525).text(asian(d) + "%");
  legendvalue6.attr('x', 520).attr('y', 555).text(black(d) + "%");
  legendvalue7.attr('x', 520).attr('y', 585).text(hispanic(d) + "%");
  legendvalue8.attr('x', 520).attr('y', 615).text(white(d) + "%");
  
  legend5.attr('x', 500).attr('y', 500).attr('width', 10)
  .attr('height', 10).attr('fill', '#F1948A');
  legend6.attr('x', 500).attr('y', 530).attr('width', 10)
  .attr('height', 10).attr('fill', '#BB8FCE');
	legend7.attr('x', 500).attr('y', 560).attr('width', 10)
  .attr('height', 10).attr('fill', '#85C1E9');
  legend8.attr('x', 500).attr('y', 590).attr('width', 10)
  .attr('height', 10).attr('fill', '#82E0AA');
  
  ethnicitybar1.attr('x', 505)
    .attr('y', 258).attr('width', 30)
  	.attr('height', (asian(d))*(2.07)).attr('fill','#F1948A');
  ethnicitybar2.attr('x', 505)
    .attr('y', 465-(white(d))*(2.07)-(hispanic(d))*(2.07)-(black(d))*(2.07)).attr('width', 30)
  	.attr('height', (black(d))*(2.07)).attr('fill', '#BB8FCE');
  ethnicitybar3.attr('x', 505)
    .attr('y', 465-(white(d))*(2.07)-(hispanic(d))*(2.07)).attr('width', 30)
  	.attr('height', (hispanic(d))*(2.07)).attr('fill', '#85C1E9');
  ethnicitybar4.attr('x', 505)
    .attr('y', 465-(white(d))*(2.07)).attr('width', 30)
  	.attr('height', (white(d))*(2.07)).attr('fill', '#82E0AA');
  
  legendlabel9.attr('x', 595).attr('y', 509).text('Grade 3');
  legendlabel10.attr('x', 595).attr('y', 540).text('Grade 4');
  legendlabel11.attr('x', 595).attr('y', 570).text('Grade 5');
  legendlabel12.attr('x', 595).attr('y', 600).text('Grade 6');
  legendlabel13.attr('x', 595).attr('y', 630).text('Grade 7');
  legendlabel14.attr('x', 595).attr('y', 660).text('Grade 8');
  
  legendvalue9.attr('x', 595).attr('y', 525).text(grade3(d) + "%");
  legendvalue10.attr('x', 595).attr('y', 555).text(grade4(d) + "%");
  legendvalue11.attr('x', 595).attr('y', 585).text(grade5(d) + "%");
  legendvalue12.attr('x', 595).attr('y', 615).text(grade6(d) + "%");
  legendvalue13.attr('x', 595).attr('y', 645).text(grade7(d) + "%");
  legendvalue14.attr('x', 595).attr('y', 675).text(grade8(d) + "%");
  
  legend9.attr('x', 575).attr('y', 500).attr('width', 10)
  .attr('height', 10).attr('fill', '#D6EAF8');
  legend10.attr('x', 575).attr('y', 530).attr('width', 10)
  .attr('height', 10).attr('fill', '#85C1E9');
	legend11.attr('x', 575).attr('y', 560).attr('width', 10)
  .attr('height', 10).attr('fill', '#5DADE2');
  legend12.attr('x', 575).attr('y', 590).attr('width', 10)
  .attr('height', 10).attr('fill', '#007AFF');
  legend13.attr('x', 575).attr('y', 620).attr('width', 10)
  .attr('height', 10).attr('fill', '#0000FF');
  legend14.attr('x', 575).attr('y', 650).attr('width', 10)
  .attr('height', 10).attr('fill', '#011F4B');
  
  gradebar3.attr('x', 585)
    .attr('y', 258).attr('width', 30)
  	.attr('height', (grade3(d))*(2.07)).attr('fill','#D6EAF8');
  gradebar4.attr('x', 585)
    .attr('y', 258+(grade3(d))*(2.07)).attr('width', 30)
  	.attr('height', (grade4(d))*(2.07)).attr('fill','#85C1E9');
  gradebar5.attr('x', 585)
    .attr('y', 465-(grade5(d))*(2.07)-(grade6(d))*(2.07)-(grade7(d))*(2.07)-(grade8(d))*(2.07)).attr('width', 30).attr('height', (grade5(d))*(2.07)).attr('fill', '#5DADE2');
  gradebar6.attr('x', 585)
    .attr('y', 465-(grade6(d))*(2.07)-(grade7(d))*(2.07)-(grade8(d))*(2.07)).attr('width', 30)
  	.attr('height', (grade6(d))*(2.07)).attr('fill', '#007AFF');
  gradebar7.attr('x', 585)
    .attr('y', 465-(grade7(d))*(2.07)-(grade8(d))*(2.07)).attr('width', 30)
  	.attr('height', (grade7(d))*(2.07)).attr('fill', '#0000FF');
  gradebar8.attr('x', 585)
    .attr('y', 465-(grade8(d))*(2.07)).attr('width', 30)
  	.attr('height', (grade8(d))*(2.07)).attr('fill', '#011F4B');
  
  legendlabel15.attr('x', 675).attr('y', 509).text('ELL');
  legendlabel16.attr('x', 675).attr('y', 540).text('Not ELL');
  legendvalue15.attr('x', 675).attr('y', 525).text(ELL(d) + "%");
  legendvalue16.attr('x', 675).attr('y', 555).text(NoELL(d) + "%");
  legend15.attr('x', 655).attr('y', 500).attr('width', 10)
  .attr('height', 10).attr('fill', '#D98880');
  legend16.attr('x', 655).attr('y', 530).attr('width', 10)
  .attr('height', 10).attr('fill', '#1A5276');
  ellbar1.attr('x', 664)
    .attr('y', 465-(NoELL(d))*(2.07)).attr('width', 30)
  	.attr('height', (NoELL(d))*(2.07)).attr('fill', '#1A5276');
  ellbar2.attr('x', 664)
    .attr('y', 258).attr('width', 30)
  	.attr('height', (ELL(d))*(2.07))
    .attr('fill','#D98880');
	}

  function mouseout2(d){
  mapLayer2.selectAll('path')
    .style('fill', 'red').style('opacity', opacity);
	}

d3.json('https://raw.githubusercontent.com/alexjalali/remotelearningedav/main/School%20Districts.geojson').then(function(mapData) {
  var features = mapData.features;

  mapLayer2.selectAll('path')
      .data(features).enter().append('path').attr('d', path)
      .attr('vector-effect', 'non-scaling-stroke').style('fill', "red")
      .style('opacity', opacity)
      .on('mouseover', mouseover2)
      .on('mouseout', mouseout2);
});
});
</script>