# Proposal

## Research topic

Our topic will be analyzing remote learning preferences for different public school districts in New York City. We will analyze race/ethnicity, grade level, poverty, gender, disability, and more variables per district and compare those to the percentage of students who prefer to work remote rather than hybrid. Doing this we hope to see patterns and relationships between remote learning preferences and other variables, and be able to draw conclusions. We will also analyze ELA (English Language Arts) test scores and math test scores for public school students by district, and take variables such as ethnicity, gender, and poverty into account, to potentially find a correlation between student preferences and test result outcomes.

Remote learning is a fairly new concept popularized by the COVID-19 pandemic. As students of Columbia University who attended part of our undergraduate education remote, we are interested in remote learning preferences for K-12 students, what factors impact it, and how remote learning changes student outcomes. Our conclusions could assist educational institutions in making decisions for online learning. It is important to make sure there is fairness for all students of all economic backgrounds in receiving an education. 

## Data availability

### Data Set 1: Learning Preference City Remote Learning (as of Jan 4, 2021)

The first dataset we will be using is Learning Preference City Remote Learning from the NYC Department of Education. It consists of total enrollment count for students who prefer remote or hybrid learning, and who have attended school in person at least once since September 2020. The samples are collected from NYC public schools grades K-12 for each district. The dataset is as of January 4, 2021 and made public on March 11, 2021. 

This dataset is formatted with 8 columns and 876 rows of observations. The columns consist of district number, disaggregation category, category, number of total enrollment, number blended, percent blended, number remote, and percent remote. District number is our key/common variable used to combine other datasets that give metrics regarding specific district numbers for the same time period. Disaggregation category is a sub variable of different categories, such as gender or grade level. Category contains the specific group of that variable. For example, if disaggregation category is gender then the category groups are female and male for that specific district. These demographics will be used for visualizations and finding patterns. Blended refers to preference towards hybrid learning, and remote refers to preference towards remote learning. 

This dataset is updated on an as needed basis. It is imported directly through the NYC Open Data website as an excel file, which is a government project providing open source data produced and used by City government, and the excel file can be imported directly to R. Students attending charter schools, receiving home or hospital instruction, pre-K students, and attending certain specific programs are not included. In order to comply with regulations of the Family Educational Rights and Privacy Act on public reporting of education outcomes, data of groups with less than 5 students enrolled are suppressed with an “s”. 

Source URL:\
https://data.cityofnewyork.us/Education/Learning-Preference-City-Remote-Learning-as-of-Jan/k5d2-tkrr

### Data Sets 2 & 3: ELA (English Language Arts) and Math Test results (as of 2022)

The second and third datasets we will be using are ELA and Math Test results for students from grade 3 to grade 8 for different districts. The datasets are collected from the NYC Department of Education, and are updated annually.

Each dataset contains 6 different subsets. All sub-datasets split the students by districts since district is the main variable for us to combine all datasets for this project. For this project, we will use data values for year 2019 (before the pandemic) and 2022 (the first time after the pandemic when all students were required to take those exams) to study the effect of how students’ previous test outcomes influence their learning choices and also how their preferences influence their learning outcomes. We will also use data values for years 2018, 2019, and 2022 to study how the pandemic changed student learning outcomes.

Specifically, for both ELA and Math Test results, the sub datasets are:\
  1. All - this dataset contains information of the test results of all students. This dataset has 1792 rows and 16 columns.\
  2. SWD - this dataset split student test results based on whether the students are SWD (students with disabilities). This dataset has 3584 rows and 16 columns.\
  3. Ethnicity - this dataset split student test results based on student race and ethnicity (Asian, Black, Hispanic, White). This dataset has 7168 rows and 16 columns.\
  4. Gender - this dataset split student test results based on student gender (male, female). This dataset has 3584 rows and 16 columns.\
  5. Econ Status - this dataset split student test results based on whether the student is economically disadvantaged. This dataset has 3584 rows and 16 columns.\
  6. ELL - this dataset split the test results based on ELL (English Language Learner) status (current ELL, ever ELL, never ELL). This dataset has 4704 rows and 16 columns.

Some Limitations of the datasets:\
  1. Compare to other datasets we will use for this project, some districts are missing (districts 75, 79, and 84). \
  2. The scale for ELA and Math exams changed in 2018. In addition, the tests for 2020 were canceled due to the pandemic, and the tests for 2021 were voluntary. Therefore, we will only use data for 2018, 2019, and 2022. \
  3. For the ethnicity dataset, other ethnicity groups such as multi-racial and native american are not included. \
  4. For the gender dataset, other genders such as cisgender, transgender, and non-binary are not included.
	
The datasets can be downloaded from the infohub of NYC Department of Education as Excel files, and can be imported to R directly. 

Source URLs:\
ELA Test Scores: https://infohub.nyced.org/docs/default-source/default-document-library/district-ela-results-2013-2022-(public).xlsx \
Math Test Scores: https://infohub.nyced.org/docs/default-source/default-document-library/district-math-results-2013-2022-(public).xlsx

### Data Set 4: Demographic Snapshot – Citywide, Borough, District, and School (as of 2022)

The fourth dataset we will be using is Demographic Snapshot – Citywide, Borough, District, and School from the NYC Department of Education, which provides data on annual enrollment at the citywide, borough, district, and school levels. We will mainly focus on the district sub-dataset and use it as a key to merge all our datasets. The data was collected for students who were enrolled in a New York City Department of Education (DOE) school in grades K–12 during School Year (SY) 2017–18  to 2021-22. 

The district sub-dataset has 43 columns and 176 rows. Enrollment data are broken down by student characteristics including Gender (female, male), Race/Ethnicity((Asian, Black, Hispanic, Multi-Racial, Native American, White, Missing Race/Ethnicity Data), Disability Status, ELL(English Language Learner) status, Poverty, and Economic Need Index (allows the City to better identify students eligible for free lunch).  

The datasets can be downloaded from the infohub of NYC Department of Education as an Excel file and can be imported to R directly. 

Source URL:\
https://infohub.nyced.org/docs/default-source/default-document-library/demographic-snapshot-2017-18-to-2021-22.xlsx





