# Results

## Packages

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(geojsonio)
library(sp)
#for pcp
library(hrbrthemes)
library(GGally)
library(viridis)
json_map <- geojson_read("https://raw.githubusercontent.com/alexjalali/remotelearningedav/main/School%20Districts.geojson", what = "sp")
```

## Try 1

```{r}
ggplot(data = df_total, aes(y = MathScores2019, x = District)) +
  geom_point() + xlab("District") + ylab("Average Math Scores in 2019") + ggtitle("Math scores by district") +
  scale_x_continuous(breaks = seq(1, 32, 1))
```

## Plot from JSON

```{r}
plot(json_map, col = "grey")
```

### 1.Normal bar plot of remote learning preferences
```{r}
p1 <- ggplot(df_total, aes(PercentRemote)) +
  geom_histogram(binwidth = 5, boundary = 60,
                 fill = "lightBlue", col = "black") +
  xlab("% Remote")+
  ggtitle("Histogram of Percent of Students who Prefer Remote Learning per District")
p1
```


### Parallel coordinates plot

```{r pcp}
#this isn't working i am going to work on this tomorrow
#highlight the clusters based on the Species column
pcpdf <- df_total %>% subset(select=c("ELAScores2019","ELAScores2022","MathScores2019","MathScores2022","remote_cat")) 

#highlight the clusters based on the remote categorical column
pcp<-ggparcoord(pcpdf, columns=1:4, groupColumn = 5, title = "Parallel Coordiantes Plot for average test scores per district, grouped by percent remote",scale = "globalminmax") 
pcp
```